### ISSUE TITLE
Grails 3.1 support

### ISSUE THREAD

**Issue by rpalcolea** [antony/grails-sendgrid#13]
Hi!

Any plans for migrating the plugin to Grails 3.1?

**Comment by antony** [comment]
Hi,

I have no plans, no. I don't use Grails any more.

However, I'm absolutely willing to take and merge pull requests, so if you feel so inclined, I'd be happy to release a 3.1 compatible version.

**Comment by rpalcolea** [comment]
Ok great,

Do you prefer that? A pull request to master with the upgrade and you push it to bintray and ask for Grails linking? Or do you want me to do it in a fork and publish it as desirable objects?

**Comment by antony** [comment]
Hi Roberto,

If you do a Pull Request I will review, merge and publish to bintray /
grails.

I will of course add you to the contributors list, also :)

Thanks,
Antony

**Comment by rpalcolea** [comment]
Awesome that sounds good :) 

I will work on it a submit a PR when ready. 

Thanks

**Comment by antony** [comment]
Okay, it's done. The publishing process for Grails 3 plugins is absolutely atrocious. But it's done, finally.
